# Chart values for the Camunda Platform 8 Helm chart in separate ingress setup.
# Note: you can change the global.image.tag version value as needed.
global:
  image:
    tag: 8.5.0
    pullSecrets:
      - name: dev-c8-registry
  postgresql:
    auth:
      password: SetThisToMakeHelmUpgradesEasy
  
# Reduce Zeebe and Gateway replicas and resources to make it run locally
zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 8Gi
  debug: true
  env:
    - name: LOGGING_LEVEL_IO_CAMUNDA_ZEEBE
      value: DEBUG
  
zeebeGateway:
  replicas: 1
  env:
    - name: ZEEBE_GATEWAY_SECURITY_AUTHENTICATION_MODE
      value: none
    - name: LOGGING_LEVEL_IO_CAMUNDA_GATEWAY
      value: DEBUG

operate:
  env:
    - name: LOGGING_LEVEL_IO_CAMUNDA_OPERATE
      value: DEBUG
  
tasklist:
  env:
    - name: LOGGING_LEVEL_IO_CAMUNDA_TASKLIST
      value: DEBUG

optimize:
  env:
    - name: LOGGING_LEVEL_IO_CAMUNDA_OPTIMIZE
  
identity:
  fullURL: "https://identity.eapbm.de"
  env:
    - name: IDENTITY_LOG_LEVEL
      value: DEBUG

identityPostgresql:
  enabled: true

identityKeycloak:
  enabled: true
  postgresql:
    enabled: true
  extraEnvVars:
    - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: KEYCLOAK_LOGLEVEL
      value: DEBUG
    - name: KC_LOG_LEVEL
      value: DEBUG
  auth:
    adminPassword: SetThisToMakeLoginEasy
    managementPassword: SetThisToMakeLoginEasy

 
webModeler:
  enabled: true
  restapi:
    mail:
      fromAddress: "no-reply@eapbm.de"
    env:
      - name: LOGGING_LEVEL_IO_GRPC
        value: TRACE
      - name: LOGGING_LEVEL_IO_CAMUNDA_MODELER
        trace: DEBUG
      fromAddress: "no-reply@eapbm.de"
      # Restapi.mail.fromName defines the name that will be displayed as the sender of emails sent by Web Modeler
      fromName: "Camunda Platform"

postgresql:
  enabled: true
 
# Reduce Elasticsearch replicas and resources to make it run locally
elasticsearch:
#  imageTag: 7.17.3  # Uncomment this line and set a value if you want to override the default chart value.
  master:
    replicaCount: 1
